# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: respire_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='respire_data.proto',
  package='',
  serialized_pb=_b('\n\x12respire_data.proto\"[\n\x07Measure\x12\x11\n\ttimestamp\x18\x01 \x02(\x05\x12\r\n\x05pm2_5\x18\x02 \x02(\x05\x12\x0c\n\x04pm10\x18\x03 \x02(\x05\x12\x0f\n\x07gps_lat\x18\x04 \x01(\x01\x12\x0f\n\x07gps_lon\x18\x05 \x01(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MEASURE = _descriptor.Descriptor(
  name='Measure',
  full_name='Measure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Measure.timestamp', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pm2_5', full_name='Measure.pm2_5', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pm10', full_name='Measure.pm10', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gps_lat', full_name='Measure.gps_lat', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gps_lon', full_name='Measure.gps_lon', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['Measure'] = _MEASURE

Measure = _reflection.GeneratedProtocolMessageType('Measure', (_message.Message,), dict(
  DESCRIPTOR = _MEASURE,
  __module__ = 'respire_data_pb2'
  # @@protoc_insertion_point(class_scope:Measure)
  ))
_sym_db.RegisterMessage(Measure)


# @@protoc_insertion_point(module_scope)
